### ISSUE TITLE
enhancements blog

### ISSUE THREAD

**Issue by paarals** [Platoniq/decidim-citiesforchange#46]
- [x] Display photo of author 
Right now, the author is shown but the profile's photo don't display correctly
![imatge](https://user-images.githubusercontent.com/40388743/110816017-41be7d00-828b-11eb-97fa-80957de2c2e7.png)
- [x] Date of publication 
It would be nice if next to the author the date of publication could be shown also (not necessary if takes too time)

**Comment by verarojman** [comment]
Closed by #47
