### ISSUE TITLE
Meetings on november and desembre don't appear in the program

### ISSUE THREAD

**Issue by paarals** [Platoniq/decidim-citiesforchange#80]
When you create a meeting in the conferences participatory spaces it appears in the program section. If you create a new meeting for november or desember, right not are not shown. 
Front (error): https://staging.citiesforchange.org/conferences/fearless-cities-2020/program/20#conference-day-tab-3
Back: (seems all correct) https://staging.citiesforchange.org/admin/conferences/fearless-cities-2020/components/20/manage/

**Comment by verarojman** [comment]
Can't reproduce, is it still happening? Could be something about the update.
